# Generated by Django 3.1.7 on 2021-06-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210412_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayListName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayListName', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
